Sync with Asus-MSM8916 changes (#2)
* msm8916-common: Disable codec2

 * Fixes the occasional lag while playing videos

BUG: 133178866
Change-Id: Ie6698604357adfb7c36d6655ea8a42aecad6b219

* msm8916-common: rootdir: Remove start set_baseband

There is not set_baseband in the device tree

* msm8916-common: Remove swapon_all on fs

* msm8916-common: Remove non-existent rootdir modules

* msm8916-common: Add init.program_bdaddr.sh to build

I forgot to add it in the d0f9afd158f2aeb25a21cbb2693aee6066d09ae2

* msm8916-common: gps: Don't call setPowerVote() in loc_cleanup()

 * For unknown reason, after kanging libs from crackling to
   fix RIL crash, QCRIL will be powered off together with GPS.
   To fix this, we have to keep modem power on when gps is
   turned off. This is hacky, but seems to be the only way to
   solve it. UX won't have any difference as framework still
   will handle it.

Change-Id: If099b9a0502574fffc54668409d77ca98ff9129a

* msm8916-common: gps: Fix for buffer overrun crash at copying nmea string

Add zero clearing of allocated nmea buffer to ensure
the nmea string is null terminated.

Change-Id: Ie36010a7d3eca16dabb3067ae891a94e4b63b10c
CRs-Fixed: 2041933

* Revert "msm8916-common: Correct GPS process group IDs"

This reverts commit e238a7e5dd8905daed24e5f5c794ca9f1a1a9a9f.

* msm8916-common: Add Configure core_ctl for sd410

With some Tune up from
 1. https://github.com/markkiths/android_device_asus_msm8916-common/commit/fa1fc07b2b626926722b869168a469853c7a9b4b
 2. https://github.com/audahadi/android_device_asus_qcom_common/commit/22024d0c9cdfeae05cf51c1fca9ad3e61d7a8fa4

* msm8916-common: {sensors, wcnss}: Use log/log instead cutils/log

I forgot to change it in da66c8e994f14747093eb95a2518e4caa0aa827c

* Renamed config_dozeAfterScreenOff

New name is config_dozeAfterScreenOffByDefault
Bug: 73178121

Change-Id: Ie3d1ea5a2cc480655592bf6e49b37f5ea07f3f58

* msm8916-common: Drop fs_config it not use anymore we use config.fs here https://github.com/markkiths/android_device_asus_msm8916-common/blob/lineage-17.1/BoardConfigCommon.mk#L115
 And asdf must be 0755 before bring up android 10 here https://github.com/Asus-MSM8916/android_device_asus_msm8916-common/blob/lineage-16.0/rootdir/etc/init.qcom.rc#L51

* msm8916-common: sepolicy: Fix program_bdaddr denials

avc: denied { execute_no_trans } for comm="init.program_bd" path="/system/vendor/bin/btnvtool" dev="mmcblk0p42" ino=4146 scontext=u:r:bluetooth_loader:s0 tcontext=u:object_r:btnvtool_exec:s0 tclass=file permissive=1
avc: denied { execute_no_trans } for path="/system/vendor/bin/btnvtool" dev="mmcblk0p42" ino=4146 scontext=u:r:bluetooth_loader:s0 tcontext=u:object_r:btnvtool_exec:s0 tclass=file permissive=1
avc: denied { getattr } for comm="btnvtool" path="/factory/bt_nv.bin" dev="mmcblk0p18" ino=21 scontext=u:r:bluetooth_loader:s0 tcontext=u:object_r:fac_file:s0 tclass=file permissive=1
avc: denied { getattr } for path="/factory/bt_nv.bin" dev="mmcblk0p18" ino=21 scontext=u:r:bluetooth_loader:s0 tcontext=u:object_r:fac_file:s0 tclass=file permissive=1

* msm8916-common: sepolicy: Fix qti_init_shell denials

avc: denied { open } for comm="hci_qcomm_init" path="/dev/diag" dev="tmpfs" ino=8258 scontext=u:r:qti_init_shell:s0 tcontext=u:object_r:diag_device:s0 tclass=chr_file permissive=1
avc: denied { open } for path="/dev/diag" dev="tmpfs" ino=8258 scontext=u:r:qti_init_shell:s0 tcontext=u:object_r:diag_device:s0 tclass=chr_file permissive=1

avc: denied { ioctl } for comm="hci_qcomm_init" path="/dev/diag" dev="tmpfs" ino=8258 ioctlcmd=20 scontext=u:r:qti_init_shell:s0 tcontext=u:object_r:diag_device:s0 tclass=chr_file permissive=1
avc: denied { ioctl } for path="/dev/diag" dev="tmpfs" ino=8258 ioctlcmd=20 scontext=u:r:qti_init_shell:s0 tcontext=u:object_r:diag_device:s0 tclass=chr_file permissive=1

avc: denied { write } for comm="hci_qcomm_init" name="qmux_bluetooth" dev="tmpfs" ino=13337 scontext=u:r:qti_init_shell:s0 tcontext=u:object_r:qmuxd_socket:s0 tclass=dir permissive=1
avc: denied { write } for name="qmux_bluetooth" dev="tmpfs" ino=13337 scontext=u:r:qti_init_shell:s0 tcontext=u:object_r:qmuxd_socket:s0 tclass=dir permissive=1

avc: denied { add_name } for comm="hci_qcomm_init" name=716D75785F636C69656E745F736F636B657420202032383735 scontext=u:r:qti_init_shell:s0 tcontext=u:object_r:qmuxd_socket:s0 tclass=dir permissive=1
avc: denied { add_name } for name=716D75785F636C69656E745F736F636B657420202032383735 scontext=u:r:qti_init_shell:s0 tcontext=u:object_r:qmuxd_socket:s0 tclass=dir permissive=1

avc: denied { create } for comm="hci_qcomm_init" name=716D75785F636C69656E745F736F636B657420202032383735 scontext=u:r:qti_init_shell:s0 tcontext=u:object_r:qmuxd_socket:s0 tclass=sock_file permissive=1
avc: denied { create } for name=716D75785F636C69656E745F736F636B657420202032383735 scontext=u:r:qti_init_shell:s0 tcontext=u:object_r:qmuxd_socket:s0 tclass=sock_file permissive=1

avc: denied { write } for comm="hci_qcomm_init" name="qmux_connect_socket" dev="tmpfs" ino=14211 scontext=u:r:qti_init_shell:s0 tcontext=u:object_r:qmuxd_socket:s0 tclass=sock_file permissive=1
avc: denied { write } for name="qmux_connect_socket" dev="tmpfs" ino=14211 scontext=u:r:qti_init_shell:s0 tcontext=u:object_r:qmuxd_socket:s0 tclass=sock_file permissive=1

avc: denied { connectto } for comm="hci_qcomm_init" path="/dev/socket/qmux_bluetooth/qmux_connect_socket" scontext=u:r:qti_init_shell:s0 tcontext=u:r:qmuxd:s0 tclass=unix_stream_socket permissive=1
avc: denied { connectto } for path="/dev/socket/qmux_bluetooth/qmux_connect_socket" scontext=u:r:qti_init_shell:s0 tcontext=u:r:qmuxd:s0 tclass=unix_stream_socket permissive=1

* msm8916-common: sepolicy: Fix label hal_authsecret_default_exec

* msm8916-common: Enable sndmonitor for audio.

Monitor sound card status and report online/offline
events back to the streams registered with it and to audio_dev.

This flag is also needed to avoid compilation errors within
the hardware/qcom/audio hal.

hardware/qcom/audio-caf/msm8952/hal/audio_hw.c:2005:13: error: unused function 'out_snd_mon_cb' [-Werror,-Wunused-function]
static void out_snd_mon_cb(void * stream, struct str_parms * parms)
            ^
hardware/qcom/audio-caf/msm8952/hal/audio_hw.c:2773:13: error: unused function 'in_snd_mon_cb' [-Werror,-Wunused-function]
static void in_snd_mon_cb(void * stream, struct str_parms * parms)
            ^
hardware/qcom/audio-caf/msm8952/hal/audio_hw.c:3952:13: error: unused function 'adev_snd_mon_cb' [-Werror,-Wunused-function]
static void adev_snd_mon_cb(void *cookie, struct str_parms *parms)

Change-Id: If9d1ac020f035ca16a04b76665e30b62da0fab25

* msm8916-common: overlay: Slightly reduce status bar paddings

* The previous (8+6)dp padding was an eyesore on our 320dp screen.
* Also align the QS header tiles with the status bar contents.

Changes:
status_bar_padding_{start,end}: 6dp -> 2dp
qs_header_tile_margin_horizontal: 0dp -> 1dp

Before: https://ibb.co/B4nfGsJ
After: https://ibb.co/GtQRTRX

Change-Id: I9de3b2c12c06e330510a226ac3c7724b5d584c98

* msm8916-common: Enable CABL by default

Enable display postprocessing ABA CABL by default on msm8916.

* msm8916-common: Move sound trigger xml's to vendor

* msm8916-common: Improve makefile

Co-authored-by: bohu <bohu@google.com>
Co-authored-by: Roker2 <dimaminko2000@gmail.com>
Co-authored-by: markkiths <markkiths@gmail.com>
Co-authored-by: Wang Han <416810799@qq.com>
Co-authored-by: Katz Yamada <kyamada@codeaurora.org>
Co-authored-by: Lucas Dupin <dupin@google.com>
Co-authored-by: Quallenauge <Hamsi2k@freenet.de>
Co-authored-by: Nich <nctrenco@gmail.com>
Co-authored-by: Krishna Chaitanya Parimi <cparimi@codeaurora.org>